apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "somnus-app.morpheus.deployment.name" . }}
  labels:
    {{- include "somnus-app.morpheus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.morpheus.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "somnus-app.morpheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.morpheus.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "somnus-app.morpheus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "somnus-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: configmap-volume
          configMap:
            name: {{ include "somnus-app.configmap.name" . }}
      containers:
        - name: {{ .Chart.Name }}-morpheus
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.morpheus.repository }}:{{ .Values.image.morpheus.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: configmap-volume
              subPath: nginx.conf
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
