apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.fullname" . }}
  labels:
    {{- include "somnus-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.frontend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.service.backend" . }}
  labels:
    {{- include "somnus-app.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.service.morpheus" . }}
  labels:
    {{- include "somnus-app.morpheus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.morpheus.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.morpheus.selectorLabels" . | nindent 4 }}

