apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.fullname" . }}-frontend
  labels:
    {{- include "somnus-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.frontend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.fullname" . }}-backend
  labels:
    {{- include "somnus-app.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "somnus-app.fullname" . }}-morpheus
  labels:
    {{- include "somnus-app.morpheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "somnus-app.morpheus.selectorLabels" . | nindent 4 }}

