image:
  repository: ${dockerRegistryService}/${name}
  pullPolicy: Always
  tag: ${version}
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /\$1
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
    nginx.org/client-max-body-size: 1g
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: ${host}
      paths:
        - path: ${pathPrefix}/?(.*)
    - host: ${commonHosts}
      paths:
        - path: /?(.*)
    - host: nebula-dev.zjvis.org
      paths:
        - path: /?(.*)
backend:
  host: "10.5.24.17"
  port: 8443
websocket:
  host: "10.5.24.17"
  port: 10246
  path: /socket.io/
deploy:
  timestamp: "${deployTimestamp}"
