image:
  pullPolicy: Always
  frontend:
    repository: ${dockerRegistryService}/${name}-frontend
    tag: ${version}
  backend:
    repository: ${dockerRegistryService}/${name}-backend
    tag: ${version}
  morpheus:
    repository: ${dockerRegistryService}/${name}-morpheus
    tag: ${version}
deploy:
  timestamp: "${deployTimestamp}"
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: morpheus.zjvis.net
      paths:
        - path: /